package com.ct.usecase.demo;

public enum ServiceCode {

    OPD_CONSULTATION,
    IPD_HOSPITALIZATION,
    EMERGENCY_CARE,
    DIAGNOSTIC_LAB,
    IMAGING_XRAY,
    IMAGING_MRI,
    IMAGING_CT,
    PHARMACY_OUTPATIENT,
    PHARMACY_INPATIENT,
    SURGERY_GENERAL,
    SURGERY_SPECIALIZED,
    MATERNITY_NORMAL,
    MATERNITY_C_SECTION,
    PEDIATRIC_CARE,
    MENTAL_HEALTH,
    PHYSIOTHERAPY,
    DENTAL_BASIC,
    DENTAL_SURGICAL,
    VISION_CHECK,
    OPTICAL_LENSES,
    ICU_CARE,
    DAY_CARE_PROCEDURE,
    HOME_HEALTHCARE,
    PREVENTIVE_HEALTH_CHECK,
    VACCINATION,
    ORGAN_TRANSPLANT,
    ONCOLOGY_CHEMO,
    ONCOLOGY_RADIATION,
    RENAL_DIALYSIS,
    AMBULANCE_SERVICE
}

