server:
  port: 8081

spring:
  application:
    name: insurance-eligibility-service

  datasource:
    url: jdbc:postgresql://localhost:5432/insurance_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: DEBUG
    org.springframework.web: INFO
    com.ct.usecase.demo: INFO
